<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1v8jK76\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1v8jK76/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1v8jK76.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1v8jK76\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1v8jK76\App_KernelDevDebugContainer([
    'container.build_hash' => '1v8jK76',
    'container.build_id' => '6e0c7d05',
    'container.build_time' => 1676376290,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1v8jK76');
