<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHrCUEHp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHrCUEHp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHrCUEHp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHrCUEHp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHrCUEHp\App_KernelDevDebugContainer([
    'container.build_hash' => 'HrCUEHp',
    'container.build_id' => '41e347dd',
    'container.build_time' => 1676465079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHrCUEHp');
