certificacion_list:
  path: /list/{obraId}/{pageLabel}-{page}/{orderLabel}-{order}-{orderBy}/{limitLabel}-{limit}/{filters}
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionGetController, pageLabel: 'page' , page: 1 , orderLabel: 'order' , order: 'createAt' , orderBy: 'desc' , limitLabel: 'rows_per_page' , limit: 10 , filters: null }
  methods:  [GET,POST]

certificacion_add:
  path: /create/{obraId}
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionAddController}
  methods:  [GET]

certificacion_create:
  path: /create
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionPostController}
  methods:  [POST]

certificacion_edit:
  path: /edit/{id}/{obraId}
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionEditController}
  methods:  [GET]

certificacion_update:
  path: /update
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionPutController}
  methods:  [POST]

certificacion_delete:
  path: /delete
  defaults: { _controller: App\Backoffice\Certificacion\Infrastructure\UserInterface\Web\CertificacionDeleteController}
  methods:  [POST]
