user_directory:
  resource: '../src/Backoffice/User/Infrastructure/UserInterface/Routes/user_routes.yaml'
  prefix: /backoffice/user

obra_directory:
  resource: '../src/Backoffice/Obra/Infrastructure/UserInterface/Routes/obra_routes.yaml'
  prefix: /backoffice/obra

certificacion_directory:
  resource: '../src/Backoffice/Certificacion/Infrastructure/UserInterface/Routes/certificacion_routes.yaml'
  prefix: /backoffice/certificacion

reset_password_request_directory:
  resource: '../src/Backoffice/Authentication/ResetPasswordRequest/Infrastructure/UserInterface/Routes/reset_password_request_routes.yaml'

delete_confirmation_modal:
  path: /backoffice/delete-confirm-modal
  defaults: { _controller: App\Shared\Infrastructure\UserInterface\Web\DeleteConfirmationModalController}
  methods:  [GET]

login:
  path: /
  defaults: { _controller: App\Backoffice\Authentication\Login\SecurityController:login}
  methods:  [GET,POST]

logout:
  path: logout
  defaults: { _controller: App\Backoffice\Authentication\Login\SecurityController:logout}

dashboard_directory:
  resource: '../src/Backoffice/Dashboard/Infrastructure/UserInterface/Routes/dashboard_routes.yaml'
  prefix: /backoffice/dashboard
  methods:  [GET]

error_page:
  path: /backoffice/error
  defaults: { _controller: App\Backoffice\ErrorPage\Infrastructure\UserInterface\Web\ErrorPageGetController}
  methods:  [GET]
