doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      App\Backoffice\User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Backoffice/User/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Backoffice\User\Domain'
        alias: App

      App\Backoffice\Empresa:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Backoffice/Empresa/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Backoffice\Empresa\Domain'
        alias: App


      App\Backoffice\Obra:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Backoffice/Obra/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Backoffice\Obra\Domain'
        alias: App


      App\Backoffice\Certificacion:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Backoffice/Certificacion/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Backoffice\Certificacion\Domain'
        alias: App


      App\Backoffice\Authentication\ResetPasswordRequest:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Backoffice/Authentication/ResetPasswordRequest/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Backoffice\Authentication\ResetPasswordRequest\Domain'
        alias: App

